//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.JoyManager
{
    [Serializable]
    public class AnyJoyMsg : Message
    {
        public const string k_RosMessageName = "joy_manager_msgs/AnyJoy";
        public override string RosMessageName => k_RosMessageName;

        //  Reports the state of a joystick and additional custom commands.
        public HeaderMsg header;
        //  timestamp in the header is the time the data is received from the joystick
        public Sensor.JoyMsg joy;
        //  the state of a joysticks axes and buttons
        public string[] modules;
        //  names of specific modules in the joy_manager
        public string[] commands;
        //  custom service commands for the different modules defined above 

        public AnyJoyMsg()
        {
            this.header = new HeaderMsg();
            this.joy = new Sensor.JoyMsg();
            this.modules = new string[0];
            this.commands = new string[0];
        }

        public AnyJoyMsg(HeaderMsg header, Sensor.JoyMsg joy, string[] modules, string[] commands)
        {
            this.header = header;
            this.joy = joy;
            this.modules = modules;
            this.commands = commands;
        }

        public static AnyJoyMsg Deserialize(MessageDeserializer deserializer) => new AnyJoyMsg(deserializer);

        private AnyJoyMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.joy = Sensor.JoyMsg.Deserialize(deserializer);
            deserializer.Read(out this.modules, deserializer.ReadLength());
            deserializer.Read(out this.commands, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.joy);
            serializer.WriteLength(this.modules);
            serializer.Write(this.modules);
            serializer.WriteLength(this.commands);
            serializer.Write(this.commands);
        }

        public override string ToString()
        {
            return "AnyJoyMsg: " +
            "\nheader: " + header.ToString() +
            "\njoy: " + joy.ToString() +
            "\nmodules: " + System.String.Join(", ", modules.ToList()) +
            "\ncommands: " + System.String.Join(", ", commands.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
